### ISSUE TITLE
Listed as running vms doesn't respond to any command

### ISSUE THREAD

**Issue by rugwirobaker** [weaveworks/ignite#159] opened 2019-07-13 09:55 UTC
I created a vm with:
```
ignite run weaveworks/ignite-ubuntu \
    --cpus 2 \
    --memory 1GB \
    --ssh \
    --name my-vm
```
Running ` ignite ps` indicates that the vm i running:
```
VM ID			IMAGE				KERNEL					CREATED	SIZE	CPUS	MEMORY		STATE	IPS		PORTS	NAME
553528ae0c253ecd	weaveworks/ignite-ubuntu:latest	weaveworks/ignite-kernel:4.19.47	27h ago	4.0 GB	2	1024.0 MB	
```
However problems arise when  I try to ssh into the machine : `ignite ssh <id/name>`:
```
~ sudo ignite ssh my-vm  
ssh: connect to host 172.17.0.2 port 22: No route to host
SSH into VM "553528ae0c253ecd" failed: external command "ssh root@172.17.0.2 -o StrictHostKeyChecking=no -i /var/lib/firecracker/vm/553528ae0c253ecd/id_553528ae0c253ecd" exited with an error: exit status 255
```
I tried deleting it without the `-f` flag and it said the vm was still running and then I tried to stop it which did not work. Upon that I added the `-flag` to the `rm` command and got this:
```
➜  ~ sudo ignite rm -f my-vm
failed to stop container for VM "553528ae0c253ecd": command ["docker" "kill" "-s" "SIGQUIT" "ignite-553528ae0c253ecd"] exited with "Error response from daemon: Cannot kill container: ignite-553528ae0c253ecd: No such container: ignite-553528ae0c253ecd\n": exit status 1

```

**Note**: that  I am running all the `ignite` commands as root including `help`

**Comment by twelho** [comment] 2019-07-15 10:55
Hi @rugwirobaker :wave:,
good catch, it seems like the container with `ignite-spawn` and Firecracker didn't start correctly.
To give us some debugging information:
1. Remove the "stuck" VM with `sudo rm -r /var/lib/firecracker/vm/553528ae0c253ecd`. This should remove the VM from `ignite ps -a`.
2. Start the VM again, but add the _debug flag_ (`-d`):
```
ignite run weaveworks/ignite-ubuntu \
    --cpus 2 \
    --memory 1GB \
    --ssh \
    --name my-vm \
    -d
```
This will prevent the Docker container from being automatically removed.
3. Show us the output of `docker logs ignite-<id>`, where `<id>` is the ID of the VM created by `ignite run`.

**Comment by rugwirobaker** [comment] 2019-07-16 00:32
It seems the issue my due to the fact my laptop lost power and the VM must have not exited properly.
That is  what happening when I force a shutdown when the VM is running. Otherwise I did not have any unusual debug message.

**Comment by luxas** [comment] 2019-07-16 11:41
Ok. For the time being, VMs are pretty ephemeral. We don't have restart support really nailed down yet
(even though it technically should work).

Can we close this issue as solved then? (As the cause was the shutdown)

**Comment by rugwirobaker** [comment] 2019-07-16 13:44
Pretty much thanks for your support , Love your work.

**Closed** 2019-07-16 14:52 UTC
Labels: area/UX, kind/support, priority/backlog
